
title: AstroPlant Development Kit
description: The citizen science space farming kit.
twitter: astroplant
authors: Arn van der Pluijm
social_logo_path: /assets/brand/astroplant-social-logo.png
social_image_path: /assets/brand/astroplant-social.png

current_version: 0.1
repo: https://github.com/urbanlink/astroplant-prototype

sass:
    sass_dir: _sass
    style: compressed
